# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Gems and plugins
gems: [emoji_for_jekyll,jekyll-timeago]

  # https://github.com/yihangho/emoji-for-jekyll
  # https://github.com/markets/jekyll-timeago

# Site settings
title: eLog
email: eresearch@jcu.edu.au
description: > # this means to ignore newlines
  eLog is the technical blog written by developers and other folk at
  James Cook University's eResearch Centre.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jcu_eresearch
github_username:  jcu-eresearch

# Build settings
markdown: kramdown
